# Generated by Django 5.2.6 on 2025-09-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('contact_info', models.CharField(max_length=100)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('BASELINE', 'Baseline Visit'), ('FOLLOWUP_1', '1st Follow-up'), ('FOLLOWUP_2', '2nd Follow-up')], max_length=20)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PsychiatristQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mental_status_exam', models.TextField()),
                ('assessment_notes', models.TextField()),
                ('risk_factors', models.TextField()),
                ('recommendations', models.TextField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatrist_questionnaire', to='core.visit')),
            ],
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_requested', models.JSONField()),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Stat')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_request', to='core.visit')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('medical_history', models.TextField()),
                ('current_medications', models.TextField()),
                ('physical_exam_findings', models.TextField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_questionnaire', to='core.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.visit')),
            ],
        ),
    ]
